# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json

apiVersion: v1
kind: Template
metadata:
  name: notifications-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: notifications
    spec:
      envName: ${ENV_NAME}
      title: notifications
      feoConfigEnabled: true
      deploymentRepo: https://github.com/RedHatInsights/notifications-frontend
      API:
        versions:
          - v1
        specs:
          - url: https://console.redhat.com/api/notifications/v1/openapi.json
            bundleLabels: ["settings"]
          - url: https://console.redhat.com/api/notifications/v2/openapi.json
            bundleLabels: ["settings"]
      frontend:
        paths:
          - /apps/notifications
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: "/apps/notifications/fed-mods.json"
        defaultDocumentTitle: Notifications | Settings
        config:
          supportCaseData:
            product: Red Hat Insights
            version: Notifications

        modules:
        - id: notifications
          module: "./RootApp"
          routes:
          - pathname: "/settings/notifications"
          - pathname: "/settings/integrations/splunk-setup"

      bundleSegments:
        - segmentId: notifications-settings
          bundleId: settings
          navItems:
            - title: Notifications
              id: notifications
              expandable: true
              routes:
              - id: notificationOverview
                icon: PlaceholderIcon
                title: Overview
                href: "/settings/notifications"
              - id: configureEvents
                title: Configure Events
                href: "/settings/notifications/configure-events"
                permissions:
                - method: loosePermissions
                  args:
                  - - integrations:*:*
                    - integrations:endpoints:write
              - id: eventLog
                title: Event Log
                href: "/settings/notifications/eventlog"
                permissions:
                - method: loosePermissions
                  args:
                  - - notifications:*:*
                    - notifications:notifications:write
              - id: myUserPreferences
                title: Notification Preferences
                href: "/settings/notifications/user-preferences"
          position: 1000

      searchEntries:
        - id: notifications
          title: Notifications
          href: /settings/notifications
          description: A standardized way of notifying users of events for supported services on the Hybrid Cloud Console.
      
      serviceTiles:
        - section: integrations-notifications
          group: settings
          id: settings-notifications
          href: /settings/notifications
          title: Notifications
          description: A standardized way of notifying users of events for supported services on the Hybrid Cloud Console.
          icon: PlaceholderIcon
        - section: systemConfiguration
          group: settings
          id: configurations-notifications
          href: /settings/notifications
          title: Notifications
          description: A standardized way of notifying users of events for supported services on the Hybrid Cloud Console.
          icon: PlaceholderIcon

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/notifications-frontend
